// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovusCapEkosistemHaritasi.DAL;

#nullable disable

namespace NovusCapEkosistemHaritasi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510031534_CreateEcosystemPointsTable")]
    partial class CreateEcosystemPointsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "42 Yazılım Okulları",
                            Icon = "school-icon.png",
                            Name = "42 Okulu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Üniversiteler",
                            Icon = "university-icon.png",
                            Name = "Üniversite"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Teknoloji Merkezleri",
                            Icon = "techhub-icon.png",
                            Name = "Teknoloji Merkezi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eğitim Merkezleri",
                            Icon = "education-icon.png",
                            Name = "Eğitim Merkezi"
                        });
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.EcosystemPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("EcosystemPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sanayi Mahallesi, 1655. Sokak, No:20, 34535 Beylikdüzü",
                            CategoryId = 1,
                            City = "İstanbul",
                            Description = "Akıllı cihazlar çağında yazılım geliştiricileri yetiştiren yenilikçi kodlama okulu.",
                            District = "Beylikdüzü",
                            Icon = "school-icon.png",
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "42 İstanbul",
                            Website = "https://42istanbul.com.tr"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Yeşilova, D130 Karayolu Caddesi, No:111, 41780 Körfez",
                            CategoryId = 1,
                            City = "Kocaeli",
                            Description = "Ücretsiz, eşit erişime açık ve yenilikçi eğitim modeliyle akredite bir yazılım okulu.",
                            District = "Körfez",
                            Icon = "school-icon.png",
                            Latitude = 40.7654,
                            Longitude = 29.940799999999999,
                            Name = "42 Kocaeli",
                            Website = "https://42kocaeli.com.tr"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Yakut Mahallesi, 950. Sokak, No:2, 06586 Etimesgut",
                            CategoryId = 1,
                            City = "Ankara",
                            Description = "Yenilikçi pedagoji ile eğitim veren, ücretsiz kodlama okulu.",
                            District = "Etimesgut",
                            Icon = "school-icon.png",
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            Name = "42 Ankara",
                            Website = "https://42ankara.com.tr"
                        });
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fas fa-home",
                            IsActive = true,
                            Order = 1,
                            Title = "Ana Sayfa",
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fas fa-map-marker-alt",
                            IsActive = true,
                            Order = 2,
                            Title = "Ekosistem Noktaları",
                            Url = "/EcosystemPoints"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fas fa-info-circle",
                            IsActive = true,
                            Order = 3,
                            Title = "Hakkımızda",
                            Url = "/Home/About"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fas fa-envelope",
                            IsActive = true,
                            Order = 4,
                            Title = "İletişim",
                            Url = "/Home/Contact"
                        });
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.PageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<p>Bu platform, Türkiye'deki teknoloji ve eğitim ekosistemini haritalandırmak amacıyla oluşturulmuştur.</p><p>Amacımız, öğrencilere, girişimcilere ve teknoloji meraklılarına, bulundukları bölgelerdeki teknoloji ve eğitim olanaklarını keşfetmelerini sağlamaktır.</p>",
                            CreatedAt = new DateTime(2025, 5, 10, 6, 15, 33, 650, DateTimeKind.Local).AddTicks(4827),
                            MetaDescription = "Türkiye'deki teknoloji ve eğitim ekosistemini haritalandıran platform",
                            PageName = "About",
                            Subtitle = "Türkiye Teknoloji ve Eğitim Ekosistemi",
                            Title = "Hakkımızda"
                        },
                        new
                        {
                            Id = 2,
                            Content = "<p>Bizimle iletişime geçmek için aşağıdaki formu doldurabilirsiniz.</p>",
                            CreatedAt = new DateTime(2025, 5, 10, 6, 15, 33, 650, DateTimeKind.Local).AddTicks(5097),
                            MetaDescription = "NovusCap Ekosistem Haritası iletişim sayfası",
                            PageName = "Contact",
                            Subtitle = "Bize Ulaşın",
                            Title = "İletişim"
                        },
                        new
                        {
                            Id = 3,
                            Content = "<p>Bu gizlilik politikası, NovusCap Ekosistem Haritası web sitesinin kullanıcılarına ait kişisel verilerin nasıl toplandığını, kullanıldığını, paylaşıldığını ve korunduğunu açıklamaktadır.</p>",
                            CreatedAt = new DateTime(2025, 5, 10, 6, 15, 33, 650, DateTimeKind.Local).AddTicks(5108),
                            MetaDescription = "NovusCap Ekosistem Haritası gizlilik politikası",
                            PageName = "Privacy",
                            Subtitle = "Gizlilik Politikamız",
                            Title = "Gizlilik Politikası"
                        });
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.EcosystemPoint", b =>
                {
                    b.HasOne("NovusCapEkosistemHaritasi.Models.Category", "Category")
                        .WithMany("EcosystemPoints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.Menu", b =>
                {
                    b.HasOne("NovusCapEkosistemHaritasi.Models.Menu", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.Category", b =>
                {
                    b.Navigation("EcosystemPoints");
                });

            modelBuilder.Entity("NovusCapEkosistemHaritasi.Models.Menu", b =>
                {
                    b.Navigation("SubMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
