// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace NovusCapEkosistemHaritasi.Migrations
{
    /// <summary>
    /// Veritabanı için ilk migration
    /// </summary>
    [DbContext(typeof(DAL.ApplicationDbContext))]
    [Migration("20240511000000_InitialCreate")]
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Markers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Website = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Latitude = table.Column<double>(type: "float", nullable: false),
                    Longitude = table.Column<double>(type: "float", nullable: false),
                    Category = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Icon = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Address = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    City = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Markers", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Markers",
                columns: new[] { "Id", "Address", "Category", "City", "Description", "Icon", "Latitude", "Longitude", "Name", "Website" },
                values: new object[] { 1, "Sanayi Mahallesi, 1655. Sokak, No:20, 34535 Beylikdüzü", "42 Okulu", "İstanbul", "Akıllı cihazlar çağında yazılım geliştiricileri yetiştiren yenilikçi kodlama okulu.", "school-icon.png", 41.0082, 28.9784, "42 İstanbul", "https://42istanbul.com.tr" });

            migrationBuilder.InsertData(
                table: "Markers",
                columns: new[] { "Id", "Address", "Category", "City", "Description", "Icon", "Latitude", "Longitude", "Name", "Website" },
                values: new object[] { 2, "Yeşilova, D130 Karayolu Caddesi, No:111, 41780 Körfez", "42 Okulu", "Kocaeli", "Ücretsiz, eşit erişime açık ve yenilikçi eğitim modeliyle akredite bir yazılım okulu.", "school-icon.png", 40.7654, 29.9408, "42 Kocaeli", "https://42kocaeli.com.tr" });

            migrationBuilder.InsertData(
                table: "Markers",
                columns: new[] { "Id", "Address", "Category", "City", "Description", "Icon", "Latitude", "Longitude", "Name", "Website" },
                values: new object[] { 3, "Yakut Mahallesi, 950. Sokak, No:2, 06586 Etimesgut", "42 Okulu", "Ankara", "Yenilikçi pedagoji ile eğitim veren, ücretsiz kodlama okulu.", "school-icon.png", 39.9334, 32.8597, "42 Ankara", "https://42ankara.com.tr" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Markers");
        }
    }
}